title: HériLoup
description: Livre de recettes
theme: just-the-docs

url: https://averlok.github.io/recettes

site_logo: "assets/images/background-removed.png"

footer_content: ""






#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
